version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - editor-network
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "8080"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 2s
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      server:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - editor-network

  web_client:
    build:
      context: ./web_client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - editor-network
    mem_limit: 4g


networks:
  editor-network:
    driver: bridge

